version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "1000:8000"
  front:
    build:
      context: ./front
    ports:
      - "2000:3000"
    env_file: ./front/.docker.env